Appointment/Appointment/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("", include("patient.urls")),
    path("admin/", admin.site.urls),
]

Appointment/patient/urls.py
from django.urls import path
from . import views

app_name = "patient"

urlpatterns = [
    path("", views.index, name="index"),
    path("register/", views.user_register, name="register"),
    path("login/", views.user_login, name="login"),
    path("logout/", views.user_logout, name="logout"),
    path("appointment/", views.appointment_view, name="appointment"),
    path(
        "appointment_success/",
        views.appointment_success,
        name="appointment_success",
    ),
    path("payment/", views.payment, name="payment"),
    # path('payment/success/', views.payment_success, name='payment_success'),
]

Appointment/templates/appointment.html
{% extends 'base.html' %}
{% block content %}
{% load static %}

<center>
    <h1>Book an Appointment</h1>
</center>
<br><br>
<div class="container">
    <div class="row">
        {% for doctor in doctors %}
        <div class="col-md-4">
            <div class="jumbotron">
                <div id="dataBox">
                    <form method="POST">
                        {% csrf_token %}
                        <p><strong>Name: {{ doctor.doctor_name }}</strong></p>
                        <p><strong>Description: {{ doctor.speciality }}</strong></p>
                        <p><strong>Select Date:</strong> <input type="date" name="app_date"></p>
                        <input type="hidden" name="doctor" value="{{ doctor.id }}">
                        <input class="btn btn-warning btn-lg" type="submit" value="Submit">
                    </form>

                </div>
            </div>
        </div>
        {% endfor %}
    </div>
</div>
{% endblock %}x

Appointment/templates/appointment_success.html
{% extends 'base.html' %}
{% block content %}
{% load static %}

<style>
    table,
    th,
    td {
        border: 1px solid white;
        border-collapse: collapse;
    }

    .btn {
        width: 100px;
    }
</style>
<center>
    <h1>Appointment Success</h1>
</center>
<br><br>
<table class="container">
    <tr>
        <th>Doctor Name</th>
        <th>Appointment Date</th>
        <th>Token </th>
        <th>Status</th>
        <th>Payment</th>
    </tr>
    {% for appointment in appointments %}
    <tr>
        <td>{{appointment.name}}</td>
        <td>{{appointment.app_date}}</td>
        <td>{{appointment.token_no}}</td>
        <td>{{appointment.status}}</td>
        <td><a class="btn btn-warning" href="{% url 'patient:payment' %}" role="button">Pay</a></td>
    </tr>
    {% endfor %}
</table>
{% endblock %}


Appointment/templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">

<head>
    <title>Home</title>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-4bw+/aepP/YC94hEpVNVgiZdgIC5+VKNBQNGCHeKRQN+PtmoHDEXuppvnDJzQIu9" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-HwwvtgBNo3bZJJLYd8oVXjrBZt8cqVSpeBNS5n7C8IVInixGAoxmnlMuBnhbgrkm"
        crossorigin="anonymous"></script>
    <title>{% block title %}{% endblock %}</title>
    <link rel="icon" href="{% static 'img/logo1.jpg' %}" type="image/x-icon">
    {% block head %}{% endblock %}
</head>

<body>
    <nav class="navbar navbar-dark bg-dark">
        <div class="container">
            <h2 class="text-uppercase text-warning mb-3">MD <span class="text-white">Polyclinic</span>
            </h2>
            <div class="jumbotron">
                <ul class="nav navbar">
                    <li class="nav-item">
                        <a href="{% url 'patient:index' %}" class="nav-link" href="">Home</a>
                    </li>
                    {% if not user.is_authenticated %}
                    <li class="nav-item">
                        <a href="{% url 'admin:index' %}" class="nav-link" href="">Admin</a>
                    </li>
                    {% endif %}
                    <li class="nav-item">
                        <a href="#about" class="nav-link" href="">About</a>
                    </li>
                    <li class="nav-item">
                        <a href="#vision" class="nav-link" href="">Vision</a>
                    </li>
                    <li class="nav-item">
                        <a href="#department" class="nav-link" href="">Departments</a>
                    </li>
                    <li class="nav-item">
                        <a href="#doctors" class="nav-link" href="">Doctors</a>
                    </li>
                    {% if user.is_authenticated %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'patient:appointment' %}">Appointment</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'patient:appointment_success' %}">History</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'patient:logout' %}">Logout</a>
                    </li>
                    {% else %}
                    <li class="nav-item">
                        <a href="{% url 'patient:register' %}" class="nav-link" href="">Register</a>
                    </li>
                    <li class="nav-item">
                        <a href="{% url 'patient:login' %}" class="nav-link" href="">Login</a>
                    </li>
                    {% endif %}
                </ul>
            </div>
        </div>
    </nav>
    {% block content %}{% endblock %}
    <hr>
    {% include 'footer.html' %}
</body>

</html>

Appointment/templates/footer.html
{% load static %}
<footer>
    <link rel="stylesheet" href="{% static 'css/footer.css' %}" />
    <div class="footer">
        <div class="image-row">
            <img src="{% static 'img/fb-icon.png' %}">
            <img src="{% static 'img/instagram-icon.png' %}">
            <img src="{% static 'img/linkedin-icon.png' %}">
            <img src="{% static 'img/twitter-icon.png' %}">
            <img src="{% static 'img/youtube-icon.png' %}">
        </div>
        <div class="frow">
            <a href="#">Contact us</a>
            <a href="#">Our Services</a>
            <a href="#">Privacy Policy</a>
            <a href="#">Terms & Conditions</a>
            <a href="#">Career</a>
        </div>
        <div class="frow">
            ©2021 MD Polyclinic | All Rights Reserved
        </div>
    </div>
</footer>

Appointment/templates/index.html
{% extends 'base.html' %}
{% block content %}
{% load static %}
<link rel="stylesheet" href="{% static 'css/index.css' %}" />
<div id="carouselExampleAutoplaying" class="carousel slide" data-bs-ride="carousel">
    <div class="carousel-inner">
        <div class="carousel-item active">
            <center><img src="{% static 'img/s1.jpg' %}" class="d-block w-20" width="65.47%" height="10%"></center>
        </div>
        <div class="carousel-item">
            <center><img src="{% static 'img/s2.jpg' %}" class="d-block w-20" width="55%" height="10%"></center>
        </div>
        <div class="carousel-item">
            <center><img src="{% static 'img/s3.jpg' %}" class="d-block w-10" width="55%" height="10%"></center>
        </div>
        <div class="carousel-item">
            <center><img src="{% static 'img/s4.jpg' %}" class="d-block w-10" width="55.52%" height="10%"></center>
        </div>
    </div>
    <hr>
    <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleAutoplaying"
        data-bs-slide="prev">
        <span class="carousel-control-prev-icon" aria-hidden="false"></span>
        <span class="visually-hidden">Previous</span>
    </button>
    <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleAutoplaying"
        data-bs-slide="next">
        <span class="carousel-control-next-icon" aria-hidden="false"></span>
        <span class="visually-hidden">Next</span>
    </button>
</div>

<div class="section" id="about">
    <div class="container">
        <div class="row">
            <div class="center">
                <div class="section-heading">
                    <h1>
                        <center>About Us</center>
                    </h1>
                </div>
                <h5>
                    <pre>
                        Welcome to MD Polyclinic, where we prioritize your health with a range of services including
                        general medicine and specialized care in cardiology,dermatology, pediatrics, orthopedics, 
                        and gynecology. Our clinic offers comprehensivediagnostic services and our dedicated team of 
                        doctors and nurses ensures personalized care and focuses on preventive health measures. Locat
                        ed conveniently, weprovide flexible hours to accommodate your schedule. Experiencecompassionate 
                         healthcare at MD Polyclinic, committed to keeping you and your family healthyand well.
                        </pre>

                </h5>
            </div>
        </div>
    </div>
</div>
<br>
<hr>
<section class="section" id="vision">
    <div class="container">
        <div class="row">
            <div class="center">
                <div class="section-heading">
                    <h1>
                        <center>Vision</center>
                    </h1>
                    <h5>
                        <pre>
                        At MD Polyclinic, we envision a healthcare center renowned for its commitment to excellence
                        in patient care, innovation in medical technology, and compassionate service. Our goal is to
                        lead in providing comprehensive healthcare solutions that prioritize patient well-being,
                        supported by a team of dedicated professionals and state-of-the-art facilities. We strive to
                        set new standards in medical practice, fostering a trusted environment where every patient
                        receives personalized attention and optimal health outcomes. With a focus on continuous
                        improvement and community health, MD Polyclinic aims to be the preferred choice for
                        individuals seeking reliable and compassionate medical care in our region.
                        </pre>

                    </h5>
                </div>
            </div>
        </div>
    </div>
</section>
<div class="'section-header" id="department">
    <center>
        <h2>Departments</h2>
    </center>
</div>
<section class="section" id="vision">
    <div class="container">
        <div class="row">
            <div class="center">
                <div class="row">
                    <div class="col-md-4">
                        <div class="jumbotron">
                            <img src="{% static 'img/Beautylogo.jpg' %}">
                            <p></p>
                            <a class="btn btn-primary btn-lg" href="#" role="button">Learn more</a>
                        </div>
                    </div>
                    <div class="col-md-4">
                        <div class="jumbotron">
                            <img src="{% static 'img/General-Surgery.jpg' %}">
                            <p>General Surgery</p>
                            <a class="btn btn-primary btn-lg" href="#" role="button">Learn more</a>
                        </div>
                    </div>
                    <div class="col-md-4">
                        <div class="jumbotron">
                            <img src="{% static 'img/Motherbaby2.jpg' %}">
                            <p>O.B.G Department</p>
                            <a class="btn btn-primary btn-lg" href="#" role="button">Learn more</a>
                        </div>
                    </div>
                    <div class="col-md-4">
                        <div class="jumbotron">
                            <img src="{% static 'img/Pediatrician.jpg' %}">
                            <p>Pediatrician</p>
                            <a class="btn btn-primary btn-lg" href="#" role="button">Learn more</a>
                        </div>
                    </div>
                    <div class="col-md-4">
                        <div class="jumbotron">
                            <img src="{% static 'img/DentalBlue.jpg' %}">
                            <p>Dental Department</p>
                            <a class="btn btn-primary btn-lg" href="#" role="button">Learn more</a>
                        </div>
                    </div>
                    <div class="col-md-4">
                        <div class="jumbotron">
                            <img src="{% static 'img/Internist.jpg' %}">
                            <p>Internist</p>
                            <a class="btn btn-primary btn-lg" href="#" role="button">Learn more</a>
                        </div>
                    </div>
                    <div class="col-md-4">
                        <div class="jumbotron">
                            <img src="{% static 'img/optical.jpg' %}">
                            <p>orthopedics</p>
                            <a class="btn btn-primary btn-lg" href="#" role="button">Learn more</a>
                        </div>
                    </div>
                    <div class="col-md-4">
                        <div class="jumbotron">
                            <img src="{% static 'img/E.N.T.jpg' %}">
                            <p>E.N.T</p>
                            <a class="btn btn-primary btn-lg" href="#" role="button">Learn more</a>
                        </div>
                    </div>
                    <div class="col-md-4">
                        <div class="jumbotron">
                            <img src="{% static 'img/GP.jpg' %}">
                            <p>G.P</p>
                            <a class="btn btn-primary btn-lg" href="#" role="button">Learn more</a>
                        </div>
                    </div>
                    <div class="col-md-4">
                        <div class="jumbotron">
                            <img src="{% static 'img/ER-1.jpg' %}">
                            <p>E.R</p>
                            <a class="btn btn-primary btn-lg" href="#" role="button">Learn more</a>
                        </div>
                    </div>
                    <div class="col-md-4">
                        <div class="jumbotron">
                            <img src="{% static 'img/Laboratory-2.jpg' %}">
                            <p>Laboratory</p>
                            <a class="btn btn-primary btn-lg" href="#" role="button">Learn more</a>
                        </div>
                    </div>
                    <div class="col-md-4">
                        <div class="jumbotron">
                            <img src="{% static 'img/xray-yellow-1.jpg' %}">
                            <p>X-Ray</p>
                            <a class="btn btn-primary btn-lg" href="#" role="button">Learn more</a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>

<br><br><br>
<div class="'section-header" id="doctors">
    <center>
        <h2>Our Doctors</h2>
    </center>
</div>
<div class="container">
    <div class="row">
        {% for doctor in doctors %}
        <div class="col-md-4">
            <div class="jumbotron">
                <div id="dataBox">
                    <p><strong>Name:</strong>{{ doctor.doctor_name }} </p>
                    <p><strong>Description:</strong> ({{ doctor.speciality }})</p>
                    <a class="btn btn-info btn-lg" href="#" role="button">Appointment</a>
                </div>
            </div>
        </div>
    </div>
    {% endfor %}
</div>
</div>


{% endblock %}

Appointment/templates/login.html
{% extends 'base.html' %}
{% block content %}
{% load static %}
<link rel="stylesheet" href="{% static 'css/login.css' %}">


<div class="container1">
    <header>Login Form</header>
    <form method="POST">
        {% csrf_token %}
        <div class="input-field">
            <input type="text" required name="username">
            <label>Username</label>
        </div>
        <div class="input-field">
            <input class="pswrd" type="password" required name="password">
            <label>Password</label>
        </div>
        <div class="button">
            <div class="inner"></div>
            <button type="submit" value="Login">LOGIN</button>
        </div>
    </form>
    <div class="auth">Or login with</div>
    <div class="links">
        <div class="facebook">
            <i class="fab fa-facebook-square"><span>Facebook</span></i>
        </div>
        <div class="google">
            <i class="fab fa-google-plus-square"><span>Google</span></i>
        </div>
    </div>
    <div class="signup">
        Not a member? <a href="">Signup now</a>
    </div>
</div>
{% endblock %}

Appointment/templates/payment.html
{% extends 'base.html' %}

{% block content %}
{% load static %}

<center>
    <h1>Make Payment</h1>
    <form action="" method="post">
        {% csrf_token %}
        <script src="https://checkout.razorpay.com/v1/checkout.js" data-key="rzp_test_1234567890"
            data-amount="{{ payment.amount }}" data-currency="INR" data-order_id="{{ payment.id }}"
            data-buttontext="Pay with Razorpay" data-name="Your Name" data-description="Test transaction" data-image=""
            data-prefill.name="" data-prefill.email="" data-theme.color="#F37254"></script>
        <input type="hidden" custom="Hidden Element" name="hidden">
    </form>
</center>

{% endblock %}

Appointment/templates/register.html
{% extends 'base.html' %}
{% load static %}

{% block title %}Registration Form{% endblock %}

{% block head %}
<!-- <link rel="stylesheet" href="{% static 'css/register.css' %}"> -->
{% endblock %}

{% block content %}
<section class="container1">
    <header>Registration Form</header>
    <!-- <form action="" method="post" novalidate>
        {% csrf_token %}
        {% for fm in form %}
        <div class="input-box">
            {{ fm.label_tag }}
            {{ fm.username.lable_tag }}
        </div>

        <div class="input-box">
            {{ form.email.label_tag }}
            {{ form.email }}

        </div>

        <div class="column">
            <div class="input-box">
                {{ form.phone.label_tag }}
                {{ form.phone }}
            </div>
            <div class="input-box">
                {{ form.dateofbirth.label_tag }}
                {{ form.dateofbirth }}
            </div>
        </div>
        <div class="gender-box">
            {{ form.gender.label_tag }}
            {{ form.gender }}

        </div>
        <div class="input-box address">
            {{ form.address.label_tag }}
            {{ form.address }}

            <div class="column">
                {{ form.country.label_tag }}
                {{ form.country }}

                {{ form.city.label_tag }}
                {{ form.city }}
            </div>
            <div class="column">
                {{ form.state.label_tag }}
                {{ form.state }}
                {{ form.pincode.label_tag }}
                {{ form.pincode }}

            </div>
            <div class="input-box address">
                {{ form.password1.label_tag }}
                {{ form.password1 }}

            </div>
            <div class="input-box address">
                {{ form.password2.label_tag }}
                {{ form.password2 }}

            </div>
        {% endfor %}
        <input type="submit" value="Register">
    </form> -->

    <form action="" method="post" novalidate>
        {% csrf_token %}
        {% for fm in form %}
        {{fm.label_tag}} {{fm}} {{fm.errors|striptags}} <br><br>
        {% endfor %}
        <input type="submit" value="Submit">
    </form>
</section>
{% endblock %}